'''
Created on 2018年3月15日
'''
import unittest
from test_cases.daily_work_plan.test_daily_work_plan import TestCases
from test_cases.HTMLTestRunner import HTMLTestRunner

if __name__ == "__main__":
    #import sys;sys.argv = ['', 'Test.testName']
    suite = unittest.TestSuite()
#     tests = [TestCases("testNewPlan")]
#     suite.addTests(tests)   # 将测试用例列表添加到测试组中
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestCases))  # loadTestsFromNames()，类似，传入列表
    
#     # 直接将结果输出到控制台
#     runner = unittest.TextTestRunner(verbosity=2)#参数：verbosity=2
#     runner.run(suite)

    # 将测试结果输出到测试报告html中
    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Daily work plan Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)